sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

language: scala

scala:
  - 2.11.7

jdk:
  - oraclejdk8

before_cache:
  - find $HOME/.sbt -name '*.lock' | xargs rm
  - find $HOME/.ivy2 -name 'ivydata-*.properties' | xargs rm

notifications:
  webhooks:
    urls:
      - YOUR_WEBHOOK_URL
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

before_deploy:
  - travis_retry git clone --depth=1 $secret_git ./secret

deploy:
  provider: script
  script: ./deploy.sh
  on:
    condition: -e ./deploy.sh
